config/routes.rb
Omrails::Application.routes.draw do
  get "users/show"

  resources :pins do
    resources :comments    
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  match 'users/:id' => 'users#show', as: :user
  
  root :to => 'pins#index'
  get 'about' =>'pages#about'

    resources :pins do
      member { post :vote }
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :pin_id, :user_id
  validates :content, presence: true
 
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
require 'open-uri'

class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url
 

  validates :description, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true,
												content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
												size: { less_than: 5.megabytes }

  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_attached_file :image, styles: { medium: "320x240>"}
  has_reputation :votes, source: :user, aggregated_by: :sum

  #has_reputaion :votes, source: :user, aggregated_by: :sum
  # remote image uploading


  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,  #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :city, :country, 
                  :authentication_token, :image, :gender
  # attr_accessible :title, :body

  has_many :pins, dependent: :destroy
  has_many :comments, :dependent => :destroy
  has_many :evaluations, class_name: "RSEvaluation", as: :source

def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.firstname = auth.info.first_name
    user.lastname = auth.info.last_name
    user.gender = auth.info.gender
    user.provider = auth.provider
    user.uid = auth.uid
    user.authentication_token = auth.credentials.access_token
    user.image = auth.info.image
  end
end

def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new(session["devise.user_attributes"], without_protection: true) do |user|
      user.attributes = params
      user.valid?
    end
  else
    super
  end
 end

def password_required?
  super && provider.blank?
end

def update_with_password(params, *options)
  if encrypted_password.blank?
    update_attributes(params, *options)
  else
    super
  end
 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  def create
    pin = Pin.find(params[:pin_id])
    @comment = pin.comments.create!(params[:comment])
    redirect_to pin_path(pin)
  end  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def all
		user = User.from_omniauth (request.env["omniauth.auth"])
		if user.persisted?
			flash.notice = "Signed in!"
			sign_in_and_redirect user, notice:"Signed in!"
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end
	alias_method :facebook, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  #voting system
  def vote
    value = params[:type] == "up" ? 1 : 0
    @pin = Pin.find(params[:id])
    @pin.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>Sample site by Kunal Kapadia</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Animalhutt", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
        	<li><%= link_to "Home", root_path %></li>
			     <li><%= link_to "About", about_path %></li>
      	</ul>


<% if user_signed_in? %>
          <ul class="nav pull-right">
            <% if current_user.image? %>
          <li class="navpic"><%= image_tag "http://graph.facebook.com/#{current_user.uid}/picture?type=small" %></li>
            <% else %>
          <li class="navpic"><%= image_tag "avatar-blank.jpg" %></li>
            <% end %>  
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown"><%= current_user.firstname %> <%= current_user.lastname %> <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              <ul>
                <li><%= link_to "My Account", user_path(current_user) %></li>
                <li><%= link_to "Add Image", new_pin_path %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>            
            </div>
          </li>
        </ul>

<% else %>
         <ul class="nav pull-right">
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => "popup" %>
                <%= link_to "Email Login", new_user_session_path %>
            </div>
          </li>
        </ul>
<% end %>

        
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Animalhutt</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
<body>
	<div id="wrap">
		<%= render 'layouts/header' %>

		
			<div id="main" class="container">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
				<%= yield %>

			</div>
	</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/_home.html.erb
<% if not user_signed_in? %>

<div class="hero-unit">
<h1>Animalhutt</h1>
			<p>
				<h3>A palce for animal lovers and their pets. Share your images with other animal lovers.</h3>
			</p>
			<p>
				<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
			</p>
</div>


<% end %>

app/views/pages/_largehome.html.erb
		<% if not user_signed_in? %>
		<div class="bimage">
			<div class="container">
			<h1>Animalhutt</h1>
			<p>
				<h3>A palce for animal lovers and their pets. Share your images with other animal lovers.</h3>
			</p>
			<p>
				<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
			</p>
			</div>
		</div>
		<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is a class to tech ruby on rails in a month. 
	<%= link_to "One Month rails", "http://onemonthrails.com" %>
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<h1>You are signed in</h1>
<% else %>
<div class="hero-unit">
<h1>Welcome to One Month Rails!</h1>
<p>
	This is the home page for my sample app for. <%= link_to "One Month Rails", "http://onemonthrails.com" %>
	<br>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
</p>
</div>


<% end %>

app/views/pins/_carousel.html.erb
<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">…</div>
    <div class="item">…</div>
    <div class="item">…</div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :image, label: "Upload an image" %>
  	<%= f.input :image_remote_url, label: "Upload an image from a URL" %>
 	<%= f.input :description, as: :text, input_html: { rows: "3" } %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_modal.html.erb
<div id="myModal<%= pin.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Posted by <%= link_to (pin.user.firstname + " " + pin.user.lastname), pin.user %></h3>
  </div>
  <div class="modal-body">
    <%= link_to image_tag(pin.image), pin %>
    <p><%= pin.description %></p> 
  </div>
  <div class="modal-footer">
    <div class="pull-left">

    <%= pluralize pin.reputation_for(:votes).to_i, "Likes" %> |
      <%= link_to "Like", vote_pin_path(pin, type: "up"), method: "post" %> |
      <%= link_to "Unlike", vote_pin_path(pin, type: "down"), method: "post" %> |
      <%= pluralize pin.reputation_for(:votes).to_i, "Likes" %> | <%= link_to (pluralize(pin.comments.count, 'comment')), pin %>
    
  </div>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), "#myModal#{pin.id}", "data-toggle" => "modal" %>
	<p>
		<%= pin.description %>
	</p>
	<p>
		Posted by <%= link_to (pin.user.firstname + " " + pin.user.lastname), pin.user %>
	</p>
	<p>
		<p><%= pluralize pin.reputation_for(:votes).to_i, "Likes" %> | <%= link_to (pluralize(pin.comments.count, 'comment')), pin %></p>
	</p>
	    <% if current_user == pin.user %>
	   		<%= link_to 'Edit', edit_pin_path(pin) %>
	    	<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
	    <% end %>
 </div>


<%= render 'pins/modal' , :pin => pin %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>


<div id="pins">
  <%= render @pins %>
</div>
<br />
<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
$('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
$('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
$('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">	
		<div class="hero-unit">
			<p>
			<%= image_tag @pin.image %>
			</p>
			<p>
				  <%= @pin.description %>
				</p>
				<p>
				  <%= link_to (@pin.user.firstname + " " + @pin.user.lastname), @pin.user %>
				</p>
				<p>
					<%= @pin.created_at.to_formatted_s :long_ordinal %>
				</p>
    <% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
				<%= link_to 'Back', pins_path %>

				<!-- Show Comments -->
        <p class="comment_header">Comments:</p>
          <% if @pin.comments.blank? %>                
            <p>No comments yet for this pin.</p>                               
          <% else %>                           
            <% @pin.comments.each do |comment| %>              
              <div class="comments">                           
                <p><%= comment.content %></p>
                <span>by <%= link_to (comment.user.firstname + " " + comment.user.lastname), @pin.user %> <%= time_ago_in_words(comment.created_at) %> ago</span>
              </div>
            <% end %>                          
          <% end %>


         <!-- Add Comments -->
            <% if user_signed_in? %>
              <p class="comment_header">Add Comment:</p>
              <span class="comment">
                <%= form_for([@pin, @pin.comments.build]) do |f| %>
                  <div class="field"><%= f.text_area :content, :cols => "30", :rows => "3" %></div>
                  <%= f.hidden_field :user_id, :value => current_user.id %>
                  <div class="actions"><%= f.submit "Add Comment", :class => "btn btn-header" %></div>
                <% end %>
              </span>
            <% else %>
              <p class="comment_header"><%= link_to 'Sign in', new_user_session_path %> to post comments.</p>                  
            <% end %>

		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="hero-unit">
<div class="row">
  <div class="span2">
    <% if @user.image? %>
      <%= image_tag "http://graph.facebook.com/#{@user.uid}/picture?type=large" %>
    <% else %>
      <%= image_tag "avatar-blank.jpg" %>	
    <% end %>  
  		<%= @user.firstname %> <%= @user.lastname %></br>
      <%= @user.gender %></br>
      <%= @user.city %></br>
      <%= @user.country %>
  	
  </div>

  <div class="span8">
  	


  </div>
</div>

 </div>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>